# Generated by Django 6.0.7 on 2026-08-09 23:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rosterentry',
            name='eligibility_note',
            field=models.CharField(blank=True, help_text='Evidence, e.g. "started 6 wks" or "added wk 14".', max_length=100),
        ),
        migrations.AddField(
            model_name='rosterentry',
            name='eligible',
            field=models.BooleanField(blank=True, default=None, help_text='Started 4+ weeks, or rostered 9+ weeks. Blank = not yet reviewed.', null=True),
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('forfeited', models.BooleanField(default=False, help_text='Burned to keep a player. Forfeited slots are skipped in the draft.')),
                ('current_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_picks', to='league.team')),
                ('original_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_picks', to='league.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='league.season')),
            ],
            options={
                'ordering': ['season', 'round', 'original_team'],
            },
        ),
        migrations.CreateModel(
            name='DraftSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_slots', to='league.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_slots', to='league.team')),
            ],
            options={
                'ordering': ['season', 'slot'],
            },
        ),
        migrations.CreateModel(
            name='KeeperSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_round', models.PositiveSmallIntegerField(blank=True, help_text='Computed by the engine on save.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('burned_pick', models.ForeignKey(blank=True, help_text='Computed by the engine on save.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='burned_by', to='league.draftpick')),
                ('roster_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeper_selections', to='league.rosterentry')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeper_selections', to='league.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeper_selections', to='league.team')),
            ],
            options={
                'ordering': ['season', 'team', 'cost_round'],
            },
        ),
        migrations.CreateModel(
            name='PickTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(help_text='When the trade was agreed.')),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks_traded_away', to='league.team')),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='league.draftpick')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_trades', to='league.season')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks_traded_for', to='league.team')),
            ],
            options={
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='draftpick',
            constraint=models.UniqueConstraint(fields=('season', 'round', 'original_team'), name='unique_pick_per_team_round'),
        ),
        migrations.AddConstraint(
            model_name='draftslot',
            constraint=models.UniqueConstraint(fields=('season', 'slot'), name='unique_slot_per_season'),
        ),
        migrations.AddConstraint(
            model_name='draftslot',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='unique_team_slot_per_season'),
        ),
        migrations.AddConstraint(
            model_name='keeperselection',
            constraint=models.UniqueConstraint(fields=('season', 'roster_entry'), name='unique_keeper_per_season'),
        ),
        migrations.AddConstraint(
            model_name='keeperselection',
            constraint=models.UniqueConstraint(condition=models.Q(('burned_pick__isnull', False)), fields=('burned_pick',), name='unique_burned_pick'),
        ),
    ]
