# Generated by Django 6.0.7 on 2026-08-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_rosterentry_eligibility_note_rosterentry_eligible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rosterentry',
            name='eligible',
            field=models.BooleanField(blank=True, default=True, help_text='Started 4+ weeks, or rostered 9+ weeks. Blank = not yet reviewed.', null=True),
        ),
    ]
