# Generated by Django 6.0.7 on 2026-08-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_backfill_eligible_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='keepers_revealed',
            field=models.BooleanField(default=False, help_text='Tick once all declarations are entered. Reveals keepers to the league.'),
        ),
    ]
