# Generated by Django 6.0.7 on 2026-08-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_season_keepers_revealed'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='adp',
            field=models.FloatField(blank=True, help_text='Average draft position, lower is earlier.', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='adp_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nfl_team',
            field=models.CharField(blank=True, help_text='Short code, e.g. KC.', max_length=4),
        ),
    ]
