# Generated by Django 6.0.7 on 2026-08-10 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_player_adp_player_adp_updated_player_nfl_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeeperPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('roster_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='league.rosterentry')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='league.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keeper_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['season', 'roster_entry'],
                'constraints': [models.UniqueConstraint(fields=('user', 'season', 'roster_entry'), name='unique_prediction_per_user')],
            },
        ),
    ]
