# Generated by Django 6.0.7 on 2026-08-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, help_text='Your note at the top of the page, e.g. "Need 8 of 10 to make it work."')),
                ('closed', models.BooleanField(default=False, help_text='Tick to stop all answering. The grid stays visible, read-only.')),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft_poll', to='league.season')),
            ],
        ),
        migrations.CreateModel(
            name='DraftPollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('label', models.CharField(blank=True, help_text='Optional aside, e.g. "after the Cowboys game".', max_length=100)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='league.draftpoll')),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddField(
            model_name='draftpoll',
            name='chosen_option',
            field=models.ForeignKey(blank=True, help_text='The time we are actually drafting at. Called out on the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_for', to='league.draftpolloption'),
        ),
        migrations.CreateModel(
            name='DraftPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'Yes'), ('maybe', 'If I have to'), ('no', 'No')], max_length=5)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='league.draftpolloption')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='league.team')),
            ],
            options={
                'ordering': ['option', 'team'],
            },
        ),
        migrations.CreateModel(
            name='DraftPollAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='league.draftpoll')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_alternatives', to='league.team')),
            ],
            options={
                'ordering': ['team__owner_name'],
                'constraints': [models.UniqueConstraint(fields=('poll', 'team'), name='unique_alternative_per_team')],
            },
        ),
        migrations.AddConstraint(
            model_name='draftpolloption',
            constraint=models.UniqueConstraint(fields=('poll', 'starts_at'), name='unique_option_per_poll'),
        ),
        migrations.AddConstraint(
            model_name='draftpollvote',
            constraint=models.UniqueConstraint(fields=('option', 'team'), name='unique_vote_per_team_option'),
        ),
    ]
