# Generated by Django 6.0.7 on 2026-08-11 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_draftpoll_draftpolloption_draftpoll_chosen_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True, help_text='Your note at the top of the ballot: what is being voted on and why.')),
                ('closed', models.BooleanField(default=False, help_text='Tick to stop all voting AND publish every vote to the league.')),
                ('effective_note', models.CharField(blank=True, help_text='When passed changes bite, e.g. "Passed changes apply to the 2026 draft".', max_length=200)),
                ('closing_note', models.TextField(blank=True, help_text='A closing observation, printed under the last proposal.')),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rules_poll', to='league.season')),
            ],
        ),
        migrations.CreateModel(
            name='RulesProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Position on the ballot. Also how proposals are referred to out loud.')),
                ('title', models.CharField(max_length=200)),
                ('rule_reference', models.CharField(blank=True, help_text='e.g. "Section 4, first bullet".', max_length=100)),
                ('current_text', models.TextField(help_text='The rule as it stands today.')),
                ('proposed_text', models.TextField(help_text='What it would say instead.')),
                ('case_for', models.TextField()),
                ('case_against', models.TextField()),
                ('note', models.TextField(blank=True, help_text='Neutral context, printed between the two cases and the radios.')),
                ('outcome', models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn')], default='', help_text='Recorded by the commissioner after the vote. Blank = not recorded yet.', max_length=9)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='league.rulespoll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RulesSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='league.rulespoll')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_suggestions', to='league.team')),
            ],
            options={
                'ordering': ['team__owner_name'],
            },
        ),
        migrations.CreateModel(
            name='RulesVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('for', 'For'), ('against', 'Against'), ('abstain', 'Abstain')], max_length=7)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='league.rulesproposal')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_votes', to='league.team')),
            ],
            options={
                'ordering': ['proposal', 'team__owner_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='rulesproposal',
            constraint=models.UniqueConstraint(fields=('poll', 'order'), name='unique_proposal_order_per_poll'),
        ),
        migrations.AddConstraint(
            model_name='rulessuggestion',
            constraint=models.UniqueConstraint(fields=('poll', 'team'), name='unique_rules_suggestion_per_team'),
        ),
        migrations.AddConstraint(
            model_name='rulesvote',
            constraint=models.UniqueConstraint(fields=('proposal', 'team'), name='unique_rules_vote_per_team'),
        ),
    ]
